matrix:
  include:
  - language: ruby
    name: Github Linguist (rvm 2.7)
    rvm: 2.7
    before_install:
    - git clone https://github.com/TravisToolbox/github-linguist
    install:
    - "./github-linguist/install.sh"
    script:
    - "./github-linguist/scan.sh"
  - language: ruby
    name: YAML Linting (rvm 2.7)
    rvm: 2.7
    before_install:
    - git clone https://github.com/TravisToolbox/yaml-lint
    install:
    - "./yaml-lint/install.sh"
    script:
    - "./yaml-lint/scan.sh"
  - language: bash
    name: Shellcheck (Bash)
    os: linux
    arch: arm64-graviton2
    before_install:
    - git clone https://github.com/TravisToolbox/shellcheck
    install:
    - "./shellcheck/install.sh"
    script:
    - "./shellcheck/scan.sh"
  - language: ruby
    name: Link Checking (rvm 2.7)
    rvm: 2.7
    env:
    - WHITELIST="https://img.shields.io"
    - EXCLUDE_FILES="CHANGELOG.md"
    before_install:
    - git clone https://github.com/TravisToolbox/awesomebot
    install:
    - "./awesomebot/install.sh"
    script:
    - "./awesomebot/scan.sh"
notifications:
  email: false
  slack:
    secure: LKo4vaQ7ehkM5sjFLUw2vg4jq8OTIyoZW+rNT46IRoiDSlgPJjNygv0NqlRg5T0Z38dVzp7DZzVzgFgOO4Jp+GmEVJXbhcWPwdnTMtpfixV9gOMWBJHIupIhqvBWKTFAVhlZVzY6n844m9b3Aw7kTlFSURGa3+jM0ARDoNMexj4XjELP/cYzR/syP/4kXGVL1rc66dfYLeTzlFKHm4aftuJlUx3CoOMMNaI8k31PwG8RSLqc8RS2aaFsUpP/ljdVoJsUfavh1m0/4+9f99ld1nXA3+aUFEnpfmI3vSs0C1UOR+Dk4S3C3lQGP8TKV70CmUcgEgwEOIf1/Tb973eGHwbAJNl6WTB7qzFeC6FG7tEQR8S2a++alGw5bC7hCPoww7nzyAQ19dcvBtgLlBdGkUZa0N67BXlbCL2LSlZFEisFOzm+qJ9x0Hsn0M1s32GQupK2IS7r1VpXQokOk9jgkbhApWRHcCa8zXElYTqoYb17H9Le4Ehhncq1U26bVUwt5WeG1rExZ64gfZVsRaIhPgp2fSt+QxKeoQ3eTR3QLyOnzLtgksnrhzbJrnh+w1Mg7bSw+YavX5+RovD8feexBs+shsIV/WWyWGt05eFkj6ozRuWH0ggghh249usSjntbXibzw8C3bqIfz+5bIJe2/1e1384FUABypsatmNTSxOI=
